import subprocess
import secrets
import shlex
import json
import sys
import re
import os

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


class Ludus:
    def __init__(self, ludus_url, ludus_token, tag, logger):
        self.logger = logger
        self.ludus_url = ludus_url.rstrip("/") if ludus_url else ""
        self.ludus_token = ludus_token
        self.verify = False
        self.force_config = True # if not, ludus only output is version
        self.tag = tag
        self.check_server_access()

    def _base_cmd(self):
        cmd = ["ludus"]

        if self.force_config:
            cmd.extend(["--config", "config.yml"])
        elif self.ludus_url:
            cmd.extend(["--url", self.ludus_url])

        if self.verify:
            cmd.append("--verify")

        cmd.append("--json")

        return cmd

    def _run(self, args, check=True, capture_output=True, text=True):
        cmd = self._base_cmd() + args
        self.logger.debug(f"Running command: {shlex.join(cmd)}")

        env = os.environ.copy()
        if self.ludus_token:
            env["LUDUS_API_KEY"] = self.ludus_token

        try:
            result = subprocess.run(
                cmd,
                capture_output=capture_output,
                text=text,
                check=check,
                env=env,
            )

            if result.stdout and result.stdout.strip():
                self.logger.debug(f"Command output: {result.stdout.strip()}")

            if result.stderr and result.stderr.strip():
                self.logger.debug(f"Command stderr: {result.stderr.strip()}")

            return result

        except subprocess.CalledProcessError as e:
            self.logger.error(f"Ludus command failed: {shlex.join(cmd)}")
            self.logger.error(f"stdout: {e.stdout.strip() if e.stdout else ''}")
            self.logger.error(f"stderr: {e.stderr.strip() if e.stderr else ''}")
            raise

    def _run_json(self, args, check=True):
        result = self._run(args, check=check)

        stdout = (result.stdout or "").strip()
        if not stdout:
            return None

        try:
            parsed = json.loads(stdout)
            #self.logger.debug(f"Parsed JSON output: {json.dumps(parsed, indent=2)}")
            return parsed
        except json.JSONDecodeError:
            self.logger.error(f"Command output is not valid JSON: {stdout}")
            raise ValueError("Invalid JSON output from ludus command")

    def _ensure_list(self, data, context):
        if data is None:
            return []
        if isinstance(data, list):
            return data
        self.logger.warning(f"Unexpected JSON format for {context}: expected list, got {type(data).__name__}")
        return []

    def check_server_access(self):
        try:
            data = self._run_json(["groups", "list"])
            if data is None:
                self.logger.debug("Ludus API access verified (empty response).")
            elif isinstance(data, list):
                self.logger.debug("Ludus API access verified.")
            else:
                self.logger.error(f"Unexpected JSON response while checking access: {type(data).__name__}")
                sys.exit(1)
        except Exception as e:
            self.logger.error(f"Error checking Ludus API access: {e}")
            sys.exit(1)

    def generate_userid_from_username(self, username):
        return username[:20].upper()

    # ------------- GROUPS LOGIC ----------------------------------------

    def create_group(self, teamname):
        return self._run_json(
            ["groups", "create", teamname, "--description", f"generated by {self.tag}"]
        )

    def delete_group(self, teamname):
        return self._run_json(["groups", "delete", teamname])

    def list_groups(self):
        data = self._run_json(["groups", "list"])
        groups = self._ensure_list(data, "groups list")

        filtered = []
        for group in groups:
            if not isinstance(group, dict):
                self.logger.warning(f"Skipping non-object item in groups list: {group}")
                continue

            if self.tag in (group.get("description") or ""):
                filtered.append(group)

        return filtered
    
    def get_group_users(self, teamname):
        data = self._run_json(["groups", "members", teamname])
        users = self._ensure_list(data, f"users in group '{teamname}'")
        return users

    # ------------- USERS LOGIC ----------------------------------------

    def create_user(self, username, teamname=None):
        user_id = self.generate_userid_from_username(username)
        password = secrets.token_urlsafe(16)

        return self._run_json([
            "users",
            "add",
            "-i", user_id,
            "-e", f"{user_id}@ludus4ctf.com",
            "-n", username,
            "-p", password,
        ])

    def delete_user_by_user_id(self, user_id):
        return self._run_json(["users", "rm", "-i", user_id])

    def delete_user_by_username(self, username):
        user = self.get_user_by_username(username)
        if user:
            return self.delete_user_by_user_id(user.get("userID"))

        self.logger.warning(f"User '{username}' not found, cannot delete.")
        return None

    def get_user_by_username(self, username):
        data = self._run_json(["users", "list"])
        users = self._ensure_list(data, "users list")

        for user in users:
            if not isinstance(user, dict):
                self.logger.warning(f"Skipping non-object item in users list: {user}")
                continue

            if user.get("name") == username:
                return user

        return None

    def list_users(self):
        # get users from groups based on tag, to avoid listing users not created by this tool
        groups = self.list_groups()
        users_in_tagged_groups = []
        for group in groups:
            group_name = group.get("name")
            if not group_name:
                self.logger.warning(f"Skipping group with missing name: {group}")
                continue

            members = self.get_group_users(group_name)
            for member in members:
                user_id = member.get("userID")
                if user_id:
                    users_in_tagged_groups.append(member)
                else:
                    self.logger.warning(f"Skipping group member with missing userID: {member}")


        filtered = []
        for user in users_in_tagged_groups:
            if not isinstance(user, dict):
                self.logger.warning(f"Skipping non-object item in users list: {user}")
                continue

            if self.tag in (user.get("description") or ""):
                filtered.append(user)

        return filtered
    
    def add_users_to_group(self, teamname, user_ids):
        for user_id in user_ids:
            self.logger.debug(f"Adding userID '{user_id}' to group '{teamname}'")
            self._run_json(["groups", "add", "user", user_id, teamname])

    def add_ranges_to_group(self, teamname, range_ids):
        for range_id in range_ids:
            self.logger.debug(f"Adding rangeID '{range_id}' to group '{teamname}'")
            self._run_json(["groups", "add", "range", range_id, teamname])

    def get_user_wireguard_config(self, user_id, public_ip=None):
        config = self._run_json(["users", "wireguard", "-u", user_id])
        if config and isinstance(config, dict):
            config_content = config.get("result",{}).get("wireGuardConfig",None)
            if public_ip:
                # Replace placeholder in config with actual public IP if provided
                # sed "Endpoint = x.x.x.x:" to "Endpoint = <public_ip>:"
                re_pattern = r"Endpoint\s*=\s*[\d\.]+:"
                config_content = re.sub(re_pattern, f"Endpoint = {public_ip}:", config_content)

            return config_content
        else:
            self.logger.warning(f"Unexpected WireGuard config format for userID '{user_id}': expected string, got {type(config).__name__}")
            return None