import requests
import secrets
import sys
import re

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


class LudusAPI:
    def __init__(self, ludus_url, ludus_token, logger):
        self.logger = logger
        # if url ends with a slash, remove it
        if ludus_url.endswith('/'):
            ludus_url = ludus_url[:-1]
        self.ludus_url = ludus_url
        self.ludus_token = ludus_token
        self.session = requests.Session()
        self.session.verify = False
        self.session.timeout = 10
        self.session.headers.update({
            'X-API-KEY': self.ludus_token,
            'Content-Type': 'application/json'
        })
        self.check_access()

    def check_access(self):
        try:
            response = self.session.get(f'{self.ludus_url}/whoami')
            response.raise_for_status()
            self.logger.debug("Ludus API access verified.")
        except requests.RequestException as e:
            self.logger.error(f"Error checking Ludus API access: {e}")
            sys.exit(1)

    def generate_userid_from_username(self, username):
        # Get the first 20 characters of the username capitalized
        return username[:20].upper()

    # -------------GROUPS LOGIC----------------------------------------

    def create_group(self, teamname):
        try:
            response = self.session.post(f'{self.ludus_url}/groups', json={'name': teamname, 'description': 'generated by ludus4ctf'})
            response.raise_for_status()
            self.logger.debug(f"Ludus group '{teamname}' created successfully.")
        except requests.RequestException as e:
            self.logger.error(f"Error creating Ludus group: {e}")
            sys.exit(1)

    def delete_group(self, teamname):
        try:
            response = self.session.delete(f'{self.ludus_url}/groups/{teamname}')
            response.raise_for_status()
            self.logger.debug(f"Ludus group '{teamname}' deleted successfully.")
        except requests.RequestException as e:
            self.logger.error(f"Error deleting Ludus group: {e}")
            sys.exit(1)

    def get_groups(self, description_filter=None):
        try:
            if description_filter:
                self.logger.debug(f"Retrieving groups with '{description_filter}' in description...")
            response = self.session.get(f'{self.ludus_url}/groups')
            response.raise_for_status()
            groups = response.json()
            if description_filter:
                groups = [group for group in groups if description_filter in group.get('description', '')]
            self.logger.debug(f"Successfully retrieved {len(groups)} groups from Ludus.")
            return groups
        except requests.RequestException as e:
            self.logger.error(f"Error retrieving groups from Ludus: {e}")
            sys.exit(1)

    def add_users_to_group(self, teamname, user_ids):
        try:
            response = self.session.post(f'{self.ludus_url}/groups/{teamname}/users', json={'userIDs': user_ids})
            response.raise_for_status()
            self.logger.debug(f"Users added to group '{teamname}' successfully.")
        except requests.RequestException as e:
            self.logger.error(f"Error adding users to Ludus group: {e}")
            sys.exit(1)

    # -------------USERS LOGIC--------------------------------------------

    def create_user(self, username, teamname):
        # Placeholder for adding a user to Ludus via API
        try:
            data = {
                "name": username,
                "userID": self.generate_userid_from_username(username),
                "isAdmin": False,
                "password": secrets.token_urlsafe(16),
                "email": f"{username}@example.com"
            }
            self.logger.debug(f"Creating user '{username}' using '{self.ludus_url}/user' with {data}...")
            response = self.session.post(f'{self.ludus_url}/user', json=data)
            response.raise_for_status()
            return response.json()
        except requests.RequestException as e:
            self.logger.error(f"Error creating user '{username}': {e}")
            sys.exit(1)

    def delete_user(self, userID):
        try:
            response = self.session.delete(f'{self.ludus_url}/user/{userID}')
            response.raise_for_status()
            self.logger.debug(f"Ludus user '{userID}' deleted successfully.")
        except requests.RequestException as e:
            self.logger.error(f"Error deleting Ludus user: {e}")
            sys.exit(1)

    def get_users(self):
        try:
            self.logger.debug(f"Retrieving all users...")
            response = self.session.get(f'{self.ludus_url}/user/all')
            response.raise_for_status()
            users = response.json()
            self.logger.debug(f"Successfully retrieved {len(users)} users from Ludus.")
            return users
        except requests.RequestException as e:
            self.logger.error(f"Error retrieving users from Ludus: {e}")
            sys.exit(1)

    def generate_wireguard_config(self, userID, public_ip=None):
        try:
            response = self.session.get(f'{self.ludus_url}/user/wireguard', params={'userID': userID})
            response.raise_for_status()
            self.logger.debug(f"Successfully retrieved WireGuard config for {userID}")
            config_data = response.json()
            # get result from response and save it to a file
            config_content = config_data.get('result', {}).get('wireGuardConfig', '')
            # Replace Endpoint = 10.12.0.15:51820 with the public IP if the option is set
            if public_ip:
                # Replace the peer IP in the config with the public IP
                regex_ip_pattern = r'(Endpoint\s*=\s*)\d{1,3}(?:\.\d{1,3}){3}:'
                config_content = re.sub(regex_ip_pattern, rf'\g<1>{public_ip}:', config_content)
            return config_content
        except requests.RequestException as e:
            self.logger.error(f"Error checking Ludus API access: {e}")
            exit(1)
